from rest_framework import serializers
from django.contrib.auth import get_user_model
from .models import Group, GroupMessage

User = get_user_model()

class GroupMemberSerializer(serializers.ModelSerializer):
    """Provides minimal, clean user detail fields for group listings."""
    class Meta:
        model = User
        fields = ['id', 'username', 'email']


class GroupSerializer(serializers.ModelSerializer):
    creator = GroupMemberSerializer(read_only=True)
    members = GroupMemberSerializer(many=True, read_only=True)
    join_code = serializers.CharField(read_only=True)

    class Meta:
        model = Group
        fields = ['id', 'name', 'description', 'creator', 'members', 'join_code', 'created_at']


class GroupMessageSerializer(serializers.ModelSerializer):
    sender_username = serializers.CharField(source='sender.username', read_only=True)
    is_system = serializers.SerializerMethodField()

    class Meta:
        model = GroupMessage
        fields = ['id', 'sender_username', 'message', 'timestamp', 'is_system']

    def get_is_system(self, obj):
        """Returns True if the message was auto-generated by the system (sender is null)."""
        return obj.sender is None