# Generated by Django 5.2.4 on 2026-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='created_at',
        ),
        migrations.AddField(
            model_name='expense',
            name='split_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENT', 'Percent')], default='EQUAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
