# Generated by Django 5.2.4 on 2026-07-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_personalexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalexpense',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income')], default='EXPENSE', max_length=10),
        ),
        migrations.AlterField(
            model_name='personalexpense',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food & Dining'), ('SHOPPING', 'Shopping'), ('UTILITIES', 'Bills & Utilities'), ('TRANSPORT', 'Transportation'), ('ENTERTAINMENT', 'Entertainment'), ('GROCERIES', 'Groceries'), ('SALARY', 'Salary / Paycheck'), ('FREELANCE', 'Freelance / Side Hustle'), ('INVESTMENT', 'Investments / Interest'), ('GIFT', 'Gifts / Allowances'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
