# Generated by Django 5.2.4 on 2026-02-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_buddy', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
