# Generated by Django 5.2.4 on 2026-10-02 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_memberships(apps, schema_editor):
    """Migrate existing group members to GroupMembership model"""
    Group = apps.get_model('groups', 'Group')
    GroupMembership = apps.get_model('groups', 'GroupMembership')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    for group in Group.objects.all():
        # Get all current members
        members = group.members.all()
        for member in members:
            # Determine role: creator is owner, others are members
            role = 'owner' if group.creator == member else 'member'
            GroupMembership.objects.create(
                group=group,
                user=member,
                role=role
            )


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmessage_is_deleted_groupmessage_is_forwarded_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Create the GroupMembership model
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
        # Step 2: Migrate existing data
        migrations.RunPython(migrate_memberships, migrations.RunPython.noop),
        # Step 3: Remove the old M2M field and add new one with through
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', through='groups.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
