# Generated by Django 5.2.4 on 2026-10-02 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupmembership_alter_group_members'),
    ]

    operations = [
    ]
