# Generated by Django 5.2.4 on 2026-10-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_groupmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
